export const USER_ROLES = Object.freeze({
  IT_ADMIN: 'IT_ADMIN',
  OPERATOR: 'OPERATOR',
  DRIVER: 'DRIVER',
});

export const USER_STATUSES = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
});

export const ASSIGNMENT_TYPES = Object.freeze({
  SPECIFIC_LOCATION: 'SPECIFIC_LOCATION',
  LANDMARK_ROUTE: 'LANDMARK_ROUTE',
});

export const ASSIGNMENT_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  ASSIGNED: 'ASSIGNED',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
});

export const ROUTE_STATUSES = Object.freeze({
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
});

export const ROUTE_STOP_STATUSES = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
});

export const ASSIGNMENT_STOP_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  SKIPPED: 'SKIPPED',
});

export const JOURNEY_STATUSES = Object.freeze({
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

export const SAMPLE_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
});

export const RECURRING_SCHEDULE_STATUSES = Object.freeze({
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  ENDED: 'ENDED',
});

export const LOCATION_EVENT_TYPES = Object.freeze({
  GPS_UPDATE: 'GPS_UPDATE',
  JOURNEY_STARTED: 'JOURNEY_STARTED',
  STOP_ARRIVED: 'STOP_ARRIVED',
  STOP_COMPLETED: 'STOP_COMPLETED',
  SAMPLE_COLLECTED: 'SAMPLE_COLLECTED',
  JOURNEY_ENDED: 'JOURNEY_ENDED',
});

export const PUSH_PROVIDERS = Object.freeze({
  FCM: 'FCM',
  WEB_PUSH: 'WEB_PUSH',
});

export const NOTIFICATION_TYPES = Object.freeze({
  ASSIGNMENT_ASSIGNED: 'ASSIGNMENT_ASSIGNED',
  ASSIGNMENT_CREATED: 'ASSIGNMENT_CREATED',
  ASSIGNMENT_UPDATED: 'ASSIGNMENT_UPDATED',
  ASSIGNMENT_REMINDER: 'ASSIGNMENT_REMINDER',
  ASSIGNMENT_CANCELLED: 'ASSIGNMENT_CANCELLED',
  ASSIGNMENT_DECLINED: 'ASSIGNMENT_DECLINED',
  JOURNEY_STARTED: 'JOURNEY_STARTED',
  JOURNEY_COMPLETED: 'JOURNEY_COMPLETED',
  SAMPLE_SUBMITTED: 'SAMPLE_SUBMITTED',
  SAMPLE_APPROVED: 'SAMPLE_APPROVED',
  SAMPLE_REJECTED: 'SAMPLE_REJECTED',
  RECURRING_ASSIGNMENT_GENERATED: 'RECURRING_ASSIGNMENT_GENERATED',
  SYSTEM: 'SYSTEM',
});

export const AUDIT_ENTITY_TYPES = Object.freeze({
  USER: 'USER',
  ASSIGNMENT: 'ASSIGNMENT',
  ROUTE: 'ROUTE',
  JOURNEY: 'JOURNEY',
  ASSIGNMENT_STOP: 'ASSIGNMENT_STOP',
  SAMPLE: 'SAMPLE',
  RECURRING_SCHEDULE: 'RECURRING_SCHEDULE',
  NOTIFICATION: 'NOTIFICATION',
  SYSTEM_SETTING: 'SYSTEM_SETTING',
});
